# Generated by Django 4.2.23 on 2025-08-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_boothreview_booth_reserved_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='20bc2112ffdc43b68a88720714b473bd', max_length=32, unique=True),
        ),
    ]
