# Generated by Django 4.2.23 on 2025-08-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='7b7d52fbf3224603b1c558013105e4f0', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='PaidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('media', 'Media'), ('security', 'Security'), ('service', 'Service Crew'), ('usher', 'Usher'), ('production', 'Production Crew'), ('health', 'Health Emergency'), ('official', 'Official'), ('moderator', 'Moderator'), ('rapporteur', 'Rapporteur')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='paid_photos/')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-30', '26-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51+', '51+')], max_length=10, null=True)),
                ('tshirt_size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tag_sent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('mpesa_code', models.CharField(max_length=20, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_applications', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.paidapplication'),
        ),
    ]
