# Generated by Django 4.2.23 on 2025-08-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ppvaccesstoken_token_paidapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='4f8776ac87be49c298a0a32f85b88fae', max_length=32, unique=True),
        ),
    ]
