# Generated by Django 4.2.23 on 2025-08-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidapplication',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='15c1eff734684b8e87a6ef244b22fdc3', max_length=32, unique=True),
        ),
    ]
