# Generated by Django 5.2.6 on 2025-09-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_paidapplication_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='660a446070c4488f8bd00d23cd0a278a', max_length=32, unique=True),
        ),
    ]
