# Generated by Django 5.2.6 on 2025-09-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='1411191bbdf94726b761010f27d9f34c', max_length=32, unique=True),
        ),
    ]
