# Generated by Django 5.2.6 on 2025-09-18 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='7ad91369f46540f198fa2e724fbf64ad', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='BoothApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tag_sent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_applications', to='events.event')),
            ],
            options={
                'unique_together': {('booth_number', 'company', 'event')},
            },
        ),
        migrations.CreateModel(
            name='BoothRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_range', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46+', '46+')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('photo', models.ImageField(upload_to='booth_photos/')),
                ('consent', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='events.boothapplication')),
            ],
        ),
    ]
