# Generated by Django 5.2.6 on 2025-09-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_ppvaccesstoken_token_boothapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='bbf36f0ff9644a3e8bf1ac40d75fad38', max_length=32, unique=True),
        ),
    ]
