# Generated by Django 5.2.6 on 2025-09-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='65cfaca181374ef2b3da1d8ccd143980', max_length=32, unique=True),
        ),
    ]
