# Generated by Django 5.2.6 on 2025-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booth_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='fe37502a81544e249922da1353862002', max_length=32, unique=True),
        ),
    ]
