# Generated by Django 5.2.6 on 2025-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_ppvaccesstoken_token_paidboothapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='1b0fd88ad9504b10971a419a9a331560', max_length=32, unique=True),
        ),
    ]
