# Generated by Django 5.2.6 on 2025-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kra_pin',
            field=models.CharField(blank=True, help_text="Customer's KRA PIN number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='kra_pin',
            field=models.CharField(blank=True, help_text="Customer's KRA PIN number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='9f7032303e68454099fc5e4dc6d20414', max_length=32, unique=True),
        ),
    ]
