# Generated by Django 5.2.6 on 2025-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_order_kra_pin_ticket_kra_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='ed5f19f7fea343abb135678307584449', max_length=32, unique=True),
        ),
    ]
