# Generated by Django 5.2.6 on 2025-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-PESA'), ('pesapal', 'Pesapal (Card/Airtel)'), ('mtn', 'MTN Mobile Money')], help_text='Payment method used for this order', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='b8b2a65ddb0b41b6a69f6a5791f59cb8', max_length=32, unique=True),
        ),
    ]
