# Generated by Django 5.2.6 on 2025-09-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_order_payment_method_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='33d9fa8f07754d2291b270bf714002fe', max_length=32, unique=True),
        ),
    ]
