# Generated by Django 5.2.6 on 2025-09-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='110c220ca26a49edb6159596de6345ed', max_length=32, unique=True),
        ),
    ]
