# Generated by Django 5.2.6 on 2025-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='aa781072dd0444b092d1bd573b770ede', max_length=32, unique=True),
        ),
    ]
