# Generated by Django 5.2.6 on 2025-09-23 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_ppvaccesstoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='49095f8510af410e9b7a6a776ab108ad', max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='boothvisit',
            unique_together={('booth', 'visitor')},
        ),
        migrations.AddIndex(
            model_name='boothvisit',
            index=models.Index(fields=['booth', 'visitor'], name='events_boot_booth_i_b3a3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='boothvisit',
            index=models.Index(fields=['booth', 'guest_email'], name='events_boot_booth_i_eeb50f_idx'),
        ),
    ]
