# Generated by Django 5.2.6 on 2025-09-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_ppvaccesstoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='booth_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booth_qrcodes/'),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='113dd35e378343fb8bd8bfef690b70b7', max_length=32, unique=True),
        ),
    ]
