# Generated by Django 5.2.6 on 2025-09-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_booth_booth_qr_code_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketscanlog',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Ticket Scan Log', 'verbose_name_plural': 'Ticket Scan Logs'},
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='dba402397d754ba8a99fff0ef3691e42', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketscanlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='events.ticket'),
        ),
        migrations.CreateModel(
            name='ScanInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Entrance, Meals 1, Meals 2', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this checkpoint', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this checkpoint is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_instances', to='events.event')),
            ],
            options={
                'verbose_name': 'Scan Instance',
                'verbose_name_plural': 'Scan Instances',
                'ordering': ['event', 'name'],
                'unique_together': {('name', 'event')},
            },
        ),
        migrations.AddField(
            model_name='ticketscanlog',
            name='scan_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='events.scaninstance'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketscanlog',
            unique_together={('ticket', 'scan_instance')},
        ),
    ]
