# Generated by Django 5.2.6 on 2025-09-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_ticketscanlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='213dd77b0ab64334a3de28c74a5b9c71', max_length=32, unique=True),
        ),
    ]
