# Generated by Django 5.2.6 on 2025-09-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='63e14c2b3c324685be56a82454f4d93e', max_length=32, unique=True),
        ),
    ]
