# Generated by Django 5.2.6 on 2025-09-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='a887c00c7d5c4f0e8cafa951356a8e66', max_length=32, unique=True),
        ),
    ]
