# Generated by Django 5.2.6 on 2025-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='c678cc7aa1884a1aa7de149668348e13', max_length=32, unique=True),
        ),
    ]
