# Generated by Django 5.2.6 on 2025-09-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='0dab3f847c07476285d26bd636b9ee41', max_length=32, unique=True),
        ),
    ]
