# Generated by Django 5.2.6 on 2025-09-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_ppvaccesstoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scaninstance',
            options={'ordering': ['event', 'name']},
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='7bd068403a844152bb96de8e256165a4', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='scaninstance',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this scan checkpoint', null=True),
        ),
        migrations.AlterField(
            model_name='scaninstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scaninstance',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketscanlog',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
