# Generated by Django 5.2.6 on 2025-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_scaninstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidboothapplication',
            name='kra_pin',
            field=models.CharField(blank=True, help_text="Customer's KRA PIN number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='7dcfff44870945b49dec6f9b15a886b8', max_length=32, unique=True),
        ),
    ]
