# Generated by Django 5.2.6 on 2025-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_paidboothapplication_kra_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidboothapplication',
            name='paid_booth_receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidboothapplication',
            name='paid_booth_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paidboothapplication',
            name='paid_booth_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='5fea87650d1649db9f00b67484ce5fce', max_length=32, unique=True),
        ),
    ]
