# Generated by Django 5.2.6 on 2025-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_paidboothapplication_paid_booth_receipt_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='aa6d24d512be4cafae337f4d347ad687', max_length=32, unique=True),
        ),
    ]
