# Generated by Django 5.2.6 on 2025-10-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='34f299bbf4194884ad2471f429142dd2', max_length=32, unique=True),
        ),
    ]
