# Generated by Django 5.2.6 on 2025-10-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_alter_ppvaccesstoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidapplication',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paidapplication',
            name='mpesa_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='5551dfd9931a4401887d5eadc9580f78', max_length=32, unique=True),
        ),
    ]
