# Generated by Django 5.2.6 on 2025-10-23 05:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_boothreview_unique_together_and_more'),
    ]

    operations = [
        # Same as boothvisit below: the database already has no unique index
        # on (booth, reviewer) - only the plain FK indexes - so Django's drop
        # would also try to recreate events_boothreview_booth_id_45891b2e,
        # which exists. "Duplicate key name". State-only.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='boothreview',
                    unique_together=set(),
                ),
            ],
        ),
        # Migration 0036 already dropped this index with RunSQL:
        #   ALTER TABLE events_boothvisit
        #   DROP INDEX events_boothvisit_booth_id_visitor_id_ebff7189_uniq;
        # RunSQL changes the database but not Django's migration state, so
        # this operation still believed the constraint was there and tried to
        # drop it a second time - "Found wrong number (0) of constraints".
        # State-only: bring Django's model state in line with the schema that
        # already exists, and issue no SQL.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='boothvisit',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='booth',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default='eff51e12051e419083f676cc4be9ef8f', max_length=32, unique=True),
        ),
    ]
