# Generated by Django 5.2.6 on 2025-10-23 05:42

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_boothreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppvaccesstoken',
            name='token',
            field=models.CharField(default=events.models.generate_token, max_length=32, unique=True),
        ),
    ]
