# Generated by Django 5.2.6 on 2025-10-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20251023_1438'),
    ]

    operations = [
    ]
