# Generated by Django 5.2.6 on 2025-10-23 21:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20251023_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Job title/position', max_length=300)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('short_bio', models.TextField(blank=True, help_text='Brief description for listing page')),
                ('full_bio', models.TextField(blank=True, help_text='Full biography')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('publications', models.TextField(blank=True, help_text='Publications, conferences, presentations')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='boothreview',
            name='has_been_edited',
        ),
        migrations.AlterField(
            model_name='boothreview',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='boothreview',
            index=models.Index(fields=['booth', 'reviewer'], name='events_boot_booth_i_87c618_idx'),
        ),
        migrations.AddIndex(
            model_name='boothreview',
            index=models.Index(fields=['booth', 'ip_address'], name='events_boot_booth_i_2dc263_idx'),
        ),
    ]
