# Generated by Django 5.2.6 on 2025-10-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_blogcategory_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='role',
            field=models.CharField(choices=[('media', 'Media'), ('security', 'Security'), ('service', 'Service Crew'), ('usher', 'Usher'), ('production', 'Production Crew'), ('health', 'Health Emergency'), ('official', 'Official'), ('moderator', 'Moderator'), ('rapporteur', 'Rapporteur'), ('panelist', 'Panelist'), ('events-agency', 'Events Agency'), ('organizing-committee', 'Organizing Committee')], max_length=20),
        ),
    ]
