# Generated by Django 5.2.6 on 2025-11-05 17:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_staffapplication_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('invoice_counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Document Counter',
                'verbose_name_plural': 'Document Counters',
            },
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], max_length=10)),
                ('document_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_email', models.EmailField(max_length=254)),
                ('sent_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.ticket')),
            ],
            options={
                'verbose_name': 'Invoice/Receipt',
                'verbose_name_plural': 'Invoices/Receipts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'ticket'], name='events_invo_documen_8f06cc_idx'), models.Index(fields=['document_number'], name='events_invo_documen_0b81b7_idx')],
            },
        ),
    ]
