# Generated by Django 5.2.6 on 2025-10-06 23:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitorStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_code', models.CharField(help_text='e.g., A01, B12', max_length=20, unique=True)),
                ('stand_name', models.CharField(help_text='Exhibitor/Company name', max_length=200)),
                ('floor_plan_x', models.IntegerField(default=0, help_text='X coordinate on floor plan')),
                ('floor_plan_y', models.IntegerField(default=0, help_text='Y coordinate on floor plan')),
                ('svg_path_id', models.CharField(blank=True, help_text='ID of SVG element', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exhibitor Stand',
                'verbose_name_plural': 'Exhibitor Stands',
                'ordering': ['stand_code'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_1_count', models.IntegerField(default=0)),
                ('rating_2_count', models.IntegerField(default=0)),
                ('rating_3_count', models.IntegerField(default=0)),
                ('rating_4_count', models.IntegerField(default=0)),
                ('rating_5_count', models.IntegerField(default=0)),
                ('unique_countries', models.IntegerField(default=0)),
                ('unique_cities', models.IntegerField(default=0)),
                ('last_review_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='exhibitor_feedback.exhibitorstand')),
            ],
            options={
                'verbose_name': 'Feedback Analytics',
                'verbose_name_plural': 'Feedback Analytics',
            },
        ),
        migrations.CreateModel(
            name='VisitorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_email', models.EmailField(db_index=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('industry', models.CharField(db_index=True, max_length=100)),
                ('rating', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='For moderation if needed')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_feedbacks', to='exhibitor_feedback.exhibitorstand')),
            ],
            options={
                'verbose_name': 'Visitor Feedback',
                'verbose_name_plural': 'Visitor Feedbacks',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['stand', '-submitted_at'], name='exhibitor_f_stand_i_f6a8eb_idx'), models.Index(fields=['visitor_email', 'stand'], name='exhibitor_f_visitor_609188_idx')],
            },
        ),
    ]
