# Generated by Django 5.2 on 2025-07-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
