# Generated by Django 5.2.6 on 2025-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_id', models.CharField(max_length=20, unique=True)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
        ),
    ]
