# Generated by Django 5.2.6 on 2025-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0004_sentinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentinvoice',
            name='holder_id',
            field=models.CharField(max_length=20),
        ),
    ]
